export const DEVELOPMENT_JOB_STATES = Object.freeze({
  RECEIVED: 'RECEIVED',
  UNDERSTANDING: 'UNDERSTANDING',
  AWAITING_CLARIFICATION: 'AWAITING_CLARIFICATION',
  INSPECTING_ORG: 'INSPECTING_ORG',
  PLANNING: 'PLANNING',
  AWAITING_IMPLEMENTATION_APPROVAL: 'AWAITING_IMPLEMENTATION_APPROVAL',
  IMPLEMENTING: 'IMPLEMENTING',
  WAITING_FOR_LOCK: 'WAITING_FOR_LOCK',
  VALIDATING: 'VALIDATING',
  CORRECTING: 'CORRECTING',
  AWAITING_DEPLOYMENT_APPROVAL: 'AWAITING_DEPLOYMENT_APPROVAL',
  DEPLOYING: 'DEPLOYING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
  CANCELLED: 'CANCELLED'
});

export const MAX_MECHANICAL_CORRECTION_ATTEMPTS = 3;

export function nextMechanicalCorrectionAttempt(job, requestedAttempt) {
  const next = Number(job?.correctionAttempt || 0) + 1;
  if (next > MAX_MECHANICAL_CORRECTION_ATTEMPTS || Number(requestedAttempt) > MAX_MECHANICAL_CORRECTION_ATTEMPTS) {
    throw correctionConflict('CORRECTION_LIMIT_REACHED', 'Mechanical correction is limited to three cycles.');
  }
  if (!Number.isInteger(Number(requestedAttempt)) || Number(requestedAttempt) !== next) {
    throw correctionConflict('STALE_CORRECTION_ATTEMPT', 'Correction attempt does not match persisted state.');
  }
  return next;
}

const transitions = new Map([
  [DEVELOPMENT_JOB_STATES.RECEIVED, [DEVELOPMENT_JOB_STATES.UNDERSTANDING, DEVELOPMENT_JOB_STATES.CANCELLED]],
  [DEVELOPMENT_JOB_STATES.UNDERSTANDING, [
    DEVELOPMENT_JOB_STATES.AWAITING_CLARIFICATION,
    DEVELOPMENT_JOB_STATES.INSPECTING_ORG,
    DEVELOPMENT_JOB_STATES.FAILED,
    DEVELOPMENT_JOB_STATES.CANCELLED
  ]],
  [DEVELOPMENT_JOB_STATES.AWAITING_CLARIFICATION, [DEVELOPMENT_JOB_STATES.UNDERSTANDING, DEVELOPMENT_JOB_STATES.CANCELLED]],
  [DEVELOPMENT_JOB_STATES.INSPECTING_ORG, [
    DEVELOPMENT_JOB_STATES.PLANNING,
    DEVELOPMENT_JOB_STATES.AWAITING_CLARIFICATION,
    DEVELOPMENT_JOB_STATES.FAILED,
    DEVELOPMENT_JOB_STATES.CANCELLED
  ]],
  [DEVELOPMENT_JOB_STATES.PLANNING, [
    DEVELOPMENT_JOB_STATES.AWAITING_IMPLEMENTATION_APPROVAL,
    DEVELOPMENT_JOB_STATES.AWAITING_CLARIFICATION,
    DEVELOPMENT_JOB_STATES.FAILED,
    DEVELOPMENT_JOB_STATES.CANCELLED
  ]],
  [DEVELOPMENT_JOB_STATES.AWAITING_IMPLEMENTATION_APPROVAL, [
    DEVELOPMENT_JOB_STATES.UNDERSTANDING,
    DEVELOPMENT_JOB_STATES.IMPLEMENTING,
    DEVELOPMENT_JOB_STATES.CANCELLED
  ]],
  [DEVELOPMENT_JOB_STATES.IMPLEMENTING, [
    DEVELOPMENT_JOB_STATES.AWAITING_CLARIFICATION,
    DEVELOPMENT_JOB_STATES.WAITING_FOR_LOCK,
    DEVELOPMENT_JOB_STATES.VALIDATING,
    DEVELOPMENT_JOB_STATES.FAILED,
    DEVELOPMENT_JOB_STATES.CANCELLED
  ]],
  [DEVELOPMENT_JOB_STATES.WAITING_FOR_LOCK, [
    DEVELOPMENT_JOB_STATES.IMPLEMENTING,
    DEVELOPMENT_JOB_STATES.FAILED,
    DEVELOPMENT_JOB_STATES.CANCELLED
  ]],
  [DEVELOPMENT_JOB_STATES.VALIDATING, [
    DEVELOPMENT_JOB_STATES.CORRECTING,
    DEVELOPMENT_JOB_STATES.AWAITING_DEPLOYMENT_APPROVAL,
    DEVELOPMENT_JOB_STATES.FAILED,
    DEVELOPMENT_JOB_STATES.CANCELLED
  ]],
  [DEVELOPMENT_JOB_STATES.CORRECTING, [
    DEVELOPMENT_JOB_STATES.VALIDATING,
    DEVELOPMENT_JOB_STATES.AWAITING_CLARIFICATION,
    DEVELOPMENT_JOB_STATES.FAILED,
    DEVELOPMENT_JOB_STATES.CANCELLED
  ]],
  [DEVELOPMENT_JOB_STATES.AWAITING_DEPLOYMENT_APPROVAL, [DEVELOPMENT_JOB_STATES.DEPLOYING, DEVELOPMENT_JOB_STATES.CANCELLED]],
  [DEVELOPMENT_JOB_STATES.DEPLOYING, [DEVELOPMENT_JOB_STATES.COMPLETED, DEVELOPMENT_JOB_STATES.FAILED]],
  [DEVELOPMENT_JOB_STATES.COMPLETED, []],
  [DEVELOPMENT_JOB_STATES.FAILED, [DEVELOPMENT_JOB_STATES.UNDERSTANDING, DEVELOPMENT_JOB_STATES.CANCELLED]],
  [DEVELOPMENT_JOB_STATES.CANCELLED, []]
]);

const statusLabels = Object.freeze({
  RECEIVED: 'Request received',
  UNDERSTANDING: 'Understanding the request',
  AWAITING_CLARIFICATION: 'Waiting for clarification',
  INSPECTING_ORG: 'Inspecting the Salesforce org',
  PLANNING: 'Preparing the implementation plan',
  AWAITING_IMPLEMENTATION_APPROVAL: 'Plan ready for review',
  IMPLEMENTING: 'Building the approved change',
  WAITING_FOR_LOCK: 'Waiting for component access',
  VALIDATING: 'Checking the solution in Salesforce',
  CORRECTING: 'Correcting validation findings',
  AWAITING_DEPLOYMENT_APPROVAL: 'Ready for deployment review',
  DEPLOYING: 'Deploying the approved change',
  COMPLETED: 'Completed',
  FAILED: 'Needs attention',
  CANCELLED: 'Cancelled',
  AWAITING_ORG_SELECTION: 'Waiting for target org selection',
  VERIFYING_ORG: 'Verifying the Salesforce org',
  ORG_VERIFICATION_FAILED: 'Org verification needs attention',
  ANALYZING_JIRA: 'Understanding the request',
  DISCOVERING_METADATA: 'Inspecting the Salesforce org',
  RETRIEVING_RELEVANT_METADATA: 'Inspecting the Salesforce org',
  ANALYZING_DEPENDENCIES: 'Preparing the implementation plan',
  AWAITING_PLAN_APPROVAL: 'Plan ready for review',
  PLAN_REJECTED: 'Plan changes requested',
  VALIDATION_FAILED: 'Validation needs attention'
});

export function assertDevelopmentTransition(from, to) {
  if (!Object.values(DEVELOPMENT_JOB_STATES).includes(to)) {
    throw conflict(`Unknown job state: ${to}`);
  }
  if (!(transitions.get(from) || []).includes(to)) {
    throw conflict(`Invalid job transition: ${from} -> ${to}`);
  }
}

export function publicDevelopmentStatus(state) {
  return statusLabels[state] || 'Status unavailable';
}

function conflict(message) {
  const error = new Error(message);
  error.statusCode = 409;
  error.code = 'INVALID_STATE_TRANSITION';
  return error;
}

function correctionConflict(code, message) {
  return Object.assign(new Error(message), { code, statusCode: 409 });
}
