export const JOB_STATES = Object.freeze({
  RECEIVED: 'RECEIVED',
  AWAITING_ORG_SELECTION: 'AWAITING_ORG_SELECTION',
  VERIFYING_ORG: 'VERIFYING_ORG',
  ORG_VERIFICATION_FAILED: 'ORG_VERIFICATION_FAILED',
  ANALYZING_JIRA: 'ANALYZING_JIRA',
  DISCOVERING_METADATA: 'DISCOVERING_METADATA',
  RETRIEVING_RELEVANT_METADATA: 'RETRIEVING_RELEVANT_METADATA',
  ANALYZING_DEPENDENCIES: 'ANALYZING_DEPENDENCIES',
  AWAITING_PLAN_APPROVAL: 'AWAITING_PLAN_APPROVAL',
  PLAN_REJECTED: 'PLAN_REJECTED',
  IMPLEMENTING: 'IMPLEMENTING',
  VALIDATING: 'VALIDATING',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  AWAITING_DEPLOYMENT_APPROVAL: 'AWAITING_DEPLOYMENT_APPROVAL',
  DEPLOYING: 'DEPLOYING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
  CANCELLED: 'CANCELLED'
});

const transitions = new Map([
  [JOB_STATES.RECEIVED, [JOB_STATES.AWAITING_ORG_SELECTION, JOB_STATES.VERIFYING_ORG, JOB_STATES.CANCELLED, JOB_STATES.FAILED]],
  [JOB_STATES.AWAITING_ORG_SELECTION, [JOB_STATES.VERIFYING_ORG, JOB_STATES.CANCELLED]],
  [JOB_STATES.VERIFYING_ORG, [JOB_STATES.ANALYZING_JIRA, JOB_STATES.ORG_VERIFICATION_FAILED, JOB_STATES.CANCELLED]],
  [JOB_STATES.ORG_VERIFICATION_FAILED, [JOB_STATES.VERIFYING_ORG, JOB_STATES.CANCELLED]],
  [JOB_STATES.ANALYZING_JIRA, [JOB_STATES.DISCOVERING_METADATA, JOB_STATES.FAILED, JOB_STATES.CANCELLED]],
  [JOB_STATES.DISCOVERING_METADATA, [JOB_STATES.RETRIEVING_RELEVANT_METADATA, JOB_STATES.FAILED, JOB_STATES.CANCELLED]],
  [JOB_STATES.RETRIEVING_RELEVANT_METADATA, [JOB_STATES.ANALYZING_DEPENDENCIES, JOB_STATES.FAILED, JOB_STATES.CANCELLED]],
  [JOB_STATES.ANALYZING_DEPENDENCIES, [JOB_STATES.AWAITING_PLAN_APPROVAL, JOB_STATES.IMPLEMENTING, JOB_STATES.FAILED, JOB_STATES.CANCELLED]],
  [JOB_STATES.AWAITING_PLAN_APPROVAL, [JOB_STATES.IMPLEMENTING, JOB_STATES.PLAN_REJECTED, JOB_STATES.CANCELLED]],
  [JOB_STATES.PLAN_REJECTED, [JOB_STATES.ANALYZING_JIRA, JOB_STATES.CANCELLED]],
  [JOB_STATES.IMPLEMENTING, [JOB_STATES.VALIDATING, JOB_STATES.FAILED, JOB_STATES.CANCELLED]],
  [JOB_STATES.VALIDATING, [JOB_STATES.AWAITING_DEPLOYMENT_APPROVAL, JOB_STATES.VALIDATION_FAILED, JOB_STATES.COMPLETED, JOB_STATES.CANCELLED]],
  [JOB_STATES.VALIDATION_FAILED, [JOB_STATES.IMPLEMENTING, JOB_STATES.VALIDATING, JOB_STATES.CANCELLED]],
  [JOB_STATES.AWAITING_DEPLOYMENT_APPROVAL, [JOB_STATES.DEPLOYING, JOB_STATES.IMPLEMENTING, JOB_STATES.CANCELLED]],
  [JOB_STATES.DEPLOYING, [JOB_STATES.COMPLETED, JOB_STATES.FAILED]],
  [JOB_STATES.FAILED, [JOB_STATES.CANCELLED]],
  [JOB_STATES.COMPLETED, []],
  [JOB_STATES.CANCELLED, []]
]);

export function assertTransition(from, to) {
  if (!Object.values(JOB_STATES).includes(to)) {
    throw conflict(`Unknown job state: ${to}`);
  }
  if (!(transitions.get(from) || []).includes(to)) {
    throw conflict(`Invalid job transition: ${from} -> ${to}`);
  }
}

function conflict(message) {
  const error = new Error(message);
  error.statusCode = 409;
  error.code = 'INVALID_STATE_TRANSITION';
  return error;
}
