import 'dotenv/config';
import { resolve } from 'node:path';

export const config = {
  port: Number(process.env.PORT || 3000),
  nodeEnv: process.env.NODE_ENV || 'development',
  agentBackend: process.env.AGENT_BACKEND || 'codex',
  redisUrl: process.env.REDIS_URL || 'redis://127.0.0.1:6379',
  queueDriver: process.env.QUEUE_DRIVER || 'redis',
  apiAuthToken: process.env.MIDDLEWARE_API_TOKEN || '',
  allowedOrigins: String(process.env.ALLOWED_ORIGINS || '').split(',').map((value) => value.trim()).filter(Boolean),
  jiraBaseUrl: process.env.JIRA_BASE_URL || '',
  jiraEmail: process.env.JIRA_EMAIL || '',
  jiraApiToken: process.env.JIRA_API_TOKEN || '',
  jiraAgentAccountId: process.env.JIRA_AGENT_ACCOUNT_ID || '',
  jiraWebhookSecret: process.env.JIRA_WEBHOOK_SECRET || '',
  jiraAllowedProjectKeys: String(process.env.JIRA_ALLOWED_PROJECT_KEYS || '').split(',').map((value) => value.trim().toUpperCase()).filter(Boolean),
  orgRegistryPath: process.env.SALESFORCE_ORG_REGISTRY_PATH || process.env.ORG_REGISTRY_PATH || resolve(process.cwd(), 'config', 'org-registry.json'),
  workspaceRoot: process.env.WORKSPACE_ROOT || resolve(process.cwd(), '..'),
  maxDependencyDepth: Number(process.env.MAX_DEPENDENCY_DEPTH || 2),
  maxRetrievedComponents: Number(process.env.MAX_METADATA_COMPONENTS || process.env.MAX_RETRIEVED_COMPONENTS || 25),
  maxMetadataSizeBytes: Number(process.env.MAX_METADATA_SIZE_BYTES || 5000000),
  maxRetrievalOperations: Number(process.env.MAX_RETRIEVAL_OPERATIONS || 5),
  validationExpiryMinutes: Number(process.env.VALIDATION_EXPIRY_MINUTES || 60),
  allowProductionDeployment: process.env.ALLOW_PRODUCTION_DEPLOYMENT === 'true',
  sfCommandTimeoutMs: Number(process.env.SF_COMMAND_TIMEOUT_MS || 120000),
  sfCliNode: process.env.SF_CLI_NODE || '',
  sfCliRun: process.env.SF_CLI_RUN || '',
  codexCommand: process.env.CODEX_COMMAND || 'codex',
  codexCommandWindows: process.env.CODEX_COMMAND_WINDOWS || 'codex.cmd',
  projectRoot: process.env.PROJECT_ROOT || resolve(process.cwd(), '..'),
  codexTimeoutMs: Number(process.env.CODEX_TIMEOUT_MS || 180000),
  maxPromptLength: Number(process.env.MAX_PROMPT_LENGTH || 8000),
  logLevel: process.env.LOG_LEVEL || 'info'
};
